# -- standard errors --

errors.prefix=
errors.suffix=<br>

# -- validator --
errors.invalid={0} is invalid.
errors.maxlength={0} can not be greater than {1} characters.
errors.minlength={0} can not be less than {1} characters.
errors.range={0} is not in the range {1} through {2}.
errors.required={0} is required.
errors.byte={0} must be an byte.
errors.date={0} is not a date.
errors.double={0} must be an double.
errors.float={0} must be an float.
errors.integer={0} must be an integer.
errors.long={0} must be an long.
errors.short={0} must be an short.
errors.creditcard={0} is not a valid credit card number.
errors.email={0} is an invalid e-mail address.
# -- other --
errors.cancel=Operation cancelled.
errors.detail={0}
errors.general=The process did not complete. Details should follow.
errors.token=Request could not be completed. Operation is not in sequence.
# -- welcome --
welcome.title=R4R Tech Soft
welcome.heading=Welcome to Simple Lottery Annotation Application
welcome.message=[<font face="Arial" size="4" color="red"><B> CAUTION: </B></font> For Play this game, age must be higher than 18 year]
welcome.age= Enter your Age(>18):
welcome.select=<strong> Please select your Lottery:</strong>
#---- Error
error.age.required=<font color="red"> Error, Age required</font>
error.shortAge.required=<font color="red">Acc. to govt policy, you are under age</font>
errr.lottery.required=<font color="red">Error, Lottery type required</font>