# -- standard errors --
errors.header=<UL>
errors.prefix=<LI>
errors.suffix=</LI>
errors.footer=</UL>
# -- validator --
errors.invalid={0} is invalid.
errors.maxlength={0} can not be greater than {1} characters.
errors.minlength={0} can not be less than {1} characters.
errors.range={0} is not in the range {1} through {2}.
errors.required={0} is required.
errors.byte={0} must be an byte.
errors.date={0} is not a date.
errors.double={0} must be an double.
errors.float={0} must be an float.
errors.integer={0} must be an integer.
errors.long={0} must be an long.
errors.short={0} must be an short.
errors.creditcard={0} is not a valid credit card number.
errors.email={0} is an invalid e-mail address.
# -- other --
errors.cancel=Operation cancelled.
errors.detail={0}
errors.general=The process did not complete. Details should follow.
errors.token=Request could not be completed. Operation is not in sequence.
# -- welcome --
welcome.title=R4R Tech Soft
welcome.heading=<font face="Arial" color="#008000">Simple Struts application connect with DataBase!</font>
welcome.message=It's easy to create Struts applications with NetBeans.
welcome.username=<font face="Arial" color="#008000"> Choose your UserName </font>
welcome.firstname=<font face="Arial" color="#008000"> Enter your First Name </font>
welcome.lastname=<font face="Arial" color="#008000"> Enter your Last Name </font>
welcome.age=<font face="Arial" color="#008000"> Enter your Age </font>
welcome.number=<font face="Arial" color="#008000"> Enter your Phone/Mobile No: </font>
#----  Error -------
error.userName=<font face="Arial" color="red"> error.userName.required </font>
error.firstName=<font face="Arial" color="red"> error.firstName.required </font>
error.lastName=<font face="Arial" color="red"> error.lastName.required </font>
error.age=<font face="Arial" color="red"> error.age.required( age must be numeric value ) </font>
error.number=<font face="Arial" color="red"> error.number.required( number must be numeric value ) </font>
error.number1=<font face="Arial" color="red"> error, number not exceed to numeric value 11 </font>
error.SQLConnectivity=<font face="Arial" color="red"> error.SQLConnectivity </font>
error.SQLException=<font face="Arial" color="red"> error.SQLException occure </font>