# -- standard errors --
errors.header=<UL>
errors.prefix=<LI>
errors.suffix=</LI>
errors.footer=</UL>
# -- validator --
errors.invalid={0} is invalid.
errors.maxlength={0} can not be greater than {1} characters.
errors.minlength={0} can not be less than {1} characters.
errors.range={0} is not in the range {1} through {2}.
errors.required={0} is required.
errors.byte={0} must be an byte.
errors.date={0} is not a date.
errors.double={0} must be an double.
errors.float={0} must be an float.
errors.integer={0} must be an integer.
errors.long={0} must be an long.
errors.short={0} must be an short.
errors.creditcard={0} is not a valid credit card number.
errors.email={0} is an invalid e-mail address.
# -- other --
errors.cancel=Operation cancelled.
errors.detail={0}
errors.general=The process did not complete. Details should follow.
errors.token=Request could not be completed. Operation is not in sequence.
# -- welcome --
welcome.title= R4R Tech Soft
welcome.heading= Welcome to Email Application! Struts Application
welcome.message=It's easy to create Struts applications with NetBeans.
welcome.userName=Enter your UserName (>11):
welcome.password=Enter your Password (>11):
welcome.name=Enter your Name (>16):
welcome.age= Enter your Age(=2):
welcome.email=Enter your Email ID (= 25):
welcome.number=Enter your Phone/Mobile (=15):
welcome.address=Enter your Address(=50):
welocme.gender=Enter your Gender:

#-- Error --
error.name.required=<font color="red">Error, Name required</font>
error.UserName.required=<font color="red">Error, UserName required</font>
error.Password.required=<font color="red">Error, Password required</font>
error.Address.required=<font color="red">Error, Address required</font>
error.Email.required=<font color="red">Error, Invalid Email Id( Email not contain '@@' && '..')</font>
error.age.required=<font color="red">Error, Age must be =2</font>
error.number.required=<font color="red">Error, Number required</font>
error.gender.required=<font color="red">Error, Please Specific u'r Gender</font>
error.usermatch.required=<font color="red">Error, UserName not Match</font>
error.passmatch.required=<font color="red">Error, Password not Match</font>