# -- standard errors --
errors.prefix=<LI>
errors.suffix=</LI>
# -- validator --
errors.invalid={0} is invalid.
errors.maxlength={0} can not be greater than {1} characters.
errors.minlength={0} can not be less than {1} characters.
errors.range={0} is not in the range {1} through {2}.
errors.required={0} is required.
errors.byte={0} must be an byte.
errors.date={0} is not a date.
errors.double={0} must be an double.
errors.float={0} must be an float.
errors.integer={0} must be an integer.
errors.long={0} must be an long.
errors.short={0} must be an short.
errors.creditcard={0} is not a valid credit card number.
errors.email={0} is an invalid e-mail address.
# -- other --
errors.cancel=Operation cancelled.
errors.detail={0}
errors.general=The process did not complete. Details should follow.
errors.token=Request could not be completed. Operation is not in sequence.
# -- welcome --
# -- welcome --
welcome.title= R4R Tech Soft
welcome.heading= Welcome to simple Login Application in struts!
welcome.message= [It's easy to create Struts applications with NetBeans]
welcome.name=Enter your Name:
welcome.password=  Enter your Password:
welcome.age= Enter your Age:(age<10)
welcome.email= Enter your E-mail Id:
#-- Error--
error.password.required=<font color="red"> Error, Enter your Password</font>
error.name.required=<font color="red"> Error, Enter your Name</font>
error.age.required=<font color="red"> Error, Age must be <10 </font>
error.Email.required=<font color="red"> Error, Invalid Email ID( don't used '@@' & '..')</font>
#-- End of file --