# -- standard errors --
errors.header=<UL>
errors.prefix=<LI>
errors.suffix=</LI>
errors.footer=</UL>
# -- validator --
errors.invalid={0} is invalid.
errors.maxlength={0} can not be greater than {1} characters.
errors.minlength={0} can not be less than {1} characters.
errors.range={0} is not in the range {1} through {2}.
errors.required={0} is required.
errors.byte={0} must be an byte.
errors.date={0} is not a date.
errors.double={0} must be an double.
errors.float={0} must be an float.
errors.integer={0} must be an integer.
errors.long={0} must be an long.
errors.short={0} must be an short.
errors.creditcard={0} is not a valid credit card number.
errors.email={0} is an invalid e-mail address.
# -- other --
errors.cancel=Operation cancelled.
errors.detail={0}
errors.general=The process did not complete. Details should follow.
errors.token=Request could not be completed. Operation is not in sequence.
# -- welcome --
welcome.title=R4R Tech Soft
welcome.heading=<font face="Arial" color="#008000">Welcome to R4R Tech Soft Solution! </font>
welcome.message=<font face="Arial" color="#008000"> [Dummy Application utilized all the Struts concepts ]</font>.
welcome.first=<font face="Arial" color="#008000"> Enter Employee Name:</font>
welcome.number=<font face="Arial" color="#008000"> Enter Social Security Number:</font>
welcome.department=<font face="Arial" color="#008000"> Enter Name of Department:</font>
welcome.joiningDate=<font face="Arial" color="#008000"> Enter the date of Joining:</font>

#-- Error in search.jsp page --
error.search.criteria.missing=<font face="Arial" color="red"> Error, search.criteria.missing </font>
error.search.ssNum.invalid=<font face="Arial" color="red"> Error, search.Social Security Number.invalid</font>

#-- Error in Insert.jsp page --
error.name.missing=<font face="Arial" color="red"> error.name.missing </font>
error.Number.missing=<font face="Arial" color="red"> error.Social Security Number.missing </font>
error.department.missing=<font face="Arial" color="red"> error.department.missing </font>
error.joiningDate.missing=<font face="Arial" color="red"> error.Date of Joining.missing </font>
error.Insert.ssNum.invalid=<font face="Arial" color="red"> error.Insert.Social Security Number.invalid </font>
error.Insert.Date.invalid=<font face="Arial" color="red"> error.Insert.Date of Joining.invalid </font>